name: maven-build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: oprypin/find-latest-tag@v1
      with:
        repository: casa-vega/simple-java-maven-app-original  # The repository to scan.
        releases-only: true  # We know that all relevant tags have a GitHub release for them.
      id: maven  # The step ID to refer to later.
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - run: mvn -B install -DnewVersion=${{ github.event.repository.name }}-${{ steps.maven.outputs.tag }}-SNAPSHOT

#  publish-snapshot:
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Set up settings.xml for GitHub Packages
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'adopt'
#          java-version: 8
#
#      - name: Publish SNAPSHOT version to GitHub Packages (we can skip tests, since we only deploy, if the build workflow succeeded)
#        run: mvn -B --no-transfer-progress deploy -DskipTests --projects cxf-spring-boot-starter
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
